name: Calendly PII Cleanup

on:
  schedule:
    # Runs at 2 AM UTC on the 1st of every month
    - cron: '0 2 1 * *'
  workflow_dispatch:  # Allows manual runs
jobs:
  cleanup-leads:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    # Replace Chrome installation step with this:
    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
        rm google-chrome-stable_current_amd64.deb
        echo "CHROME_VERSION=$(google-chrome --version)" >> $GITHUB_ENV

    - name: Run Calendly PII Cleanup
      env:
        EMAIL_TEST: ${{ secrets.EMAIL_TEST }}
        PASS_TEST: ${{ secrets.PASS_TEST }}
      run: python calendly_automation.py
